# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-statusline" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "33d6250373f5662aa4d707a6d92851df68108e8ab27891c2c74f05c04377b166"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "62fecb9071b72d0687620f1eb28a68920d349abd4c16ada2cc9e3f1854204017"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f02f0fdc12d679959b246d9fef141eb43c210f19a5b17b49e63cec213ca7f2f6"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "49c088f9e4fa88d5abb54d67cc0e3e540d252d7021b5fd1a83bed3f4483aa0e8"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-linux-arm64.tar.gz"
    end
  end

  name "cc-statusline"
  desc "A small, fast statusline for Claude Code"
  homepage "https://github.com/leffen/cc-statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-statusline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-statusline"]
    end
  end

  # No zap stanza required

end
