# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-statusline" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "917f4b2077df07ec929664148f2d5a493cd6a6005db5bee021b8034d40cd5c85"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "50194ae580260e750067060945da77094e214fcd964ed1ae13d4bf87a33bfe98"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c89b06873ce3ff2997c53b2098114cb24fb39e0b6848be16a19edf5ec33be06"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "228f297eba9a21f98c3a538db96840cbb6020c1eea24cd625c3e989bdb056f03"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-linux-arm64.tar.gz"
    end
  end

  name "cc-statusline"
  desc "A small, fast statusline for Claude Code"
  homepage "https://github.com/leffen/cc-statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-statusline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-statusline"]
    end
  end

  # No zap stanza required

end
