# This file was generated by GoReleaser. DO NOT EDIT.
cask "cc-statusline" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "5b98b2f46025363179794301b6ccb160600ffac74a22d6f566ecbee1597c7f1d"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "5813a9047b321f47f16aedc92c2bf3b736fd36a25c92ff0fa8f220c8fb93b9a4"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5064789a1ee14f9d958fcdf3bc3878ecb2b9553fabb56e7741cc81e6a880d8b3"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "bb1536672ffcdd82bccf80f1dcac98df2b36a3b98bdd25a063dfbb742f8cfd02"
      url "https://github.com/leffen/cc-statusline/releases/download/v#{version}/cc-statusline-linux-arm64.tar.gz"
    end
  end

  name "cc-statusline"
  desc "A small, fast statusline for Claude Code"
  homepage "https://github.com/leffen/cc-statusline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cc-statusline"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cc-statusline"]
    end
  end

  # No zap stanza required

end
