# This file was generated by GoReleaser. DO NOT EDIT.
cask "devlog" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "7d01c5e6cb0f06efdbb5fe5027df0c255a401039b4320cb79688dc3142d94d18"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b5005c86a935a42563e9e606a840852602e682210624387d00100ee641e05026"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6cc3908d32a1b25edb4d358f70a8b7474d4b108bc50e8796cabde2a439ab452"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8908cd913cfbab14499b4da21d4de086e9135f36cd7046797a7bf886e7f445f"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devlog"
  desc "CLI tool for DevLog Daily - Journal your development progress"
  homepage "https://devlog.asd09.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devlog"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devlog"]
    end
  end

  # No zap stanza required

end
