# This file was generated by GoReleaser. DO NOT EDIT.
cask "devlog" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "e9c42360220b1b430a220710d2ab8aa2001d806d401a5945cd6c905d7701b5da"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "64aaeca5acd4b3945bbd4a01884f26f168bb25a7ac5e67334e6585fd375e0a68"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76f085657111e545dd8b2d9d36db09940ac7da620d4a90ff65c69d883529abe6"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ebcbf849201690ca095636c50fe5a3e4267e4cc26981e9ca1e3386c74e332b53"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devlog"
  desc "CLI tool for DevLog Daily - Journal your development progress"
  homepage "https://devlog.asd09.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devlog"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devlog"]
    end
  end

  # No zap stanza required

end
