# This file was generated by GoReleaser. DO NOT EDIT.
cask "devlog" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "906e2bed7a020c6094c586f47deb8a524320a5a932fe249f712930d3c4092059"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1cd66ccf376ced56c40453d272f375a2f0c34f9ae019b91595123cac8e44a9c3"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "86dfec0d6f74662f7ace6c3abb73e06e7796c10ee31f724eefda1293da0849d7"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c43d5a887fc450263302efbe460a57d6b3ff17ee9d4f29292c0aafafca213a75"
      url "https://github.com/leffen/devlog-cli/releases/download/v#{version}/devlog_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devlog"
  desc "CLI tool for DevLog Daily - Journal your development progress"
  homepage "https://devlog.asd09.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devlog"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devlog"]
    end
  end

  # No zap stanza required

end
