# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devlog < Formula
  desc "CLI tool for DevLog Daily - Journal your development progress"
  homepage "https://devlog.asd09.com"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.3.0/devlog_0.3.0_darwin_amd64.tar.gz"
      sha256 "456045f1d666db53f548187d26e50acdb43a5480ea2610963b66c836c4fa3736"

      def install
        bin.install "devlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.3.0/devlog_0.3.0_darwin_arm64.tar.gz"
      sha256 "91ce03e25928816184b75517b722137c7da608ffbab76762b97b282e165aea19"

      def install
        bin.install "devlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.3.0/devlog_0.3.0_linux_amd64.tar.gz"
      sha256 "dcbf83a6d64f03dd8b04ae2e030f6b41816dce37bc94907a01f0038ca115c95e"
      def install
        bin.install "devlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.3.0/devlog_0.3.0_linux_arm64.tar.gz"
      sha256 "fa290663043435eec99a5d95ab277c2459f261795cb196541731db9cc32f4b57"
      def install
        bin.install "devlog"
      end
    end
  end

  test do
    system "#{bin}/devlog", "--version"
  end
end
