# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devlog < Formula
  desc "CLI tool for DevLog Daily - Journal your development progress"
  homepage "https://devlog.asd09.com"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.7.0/devlog_0.7.0_darwin_amd64.tar.gz"
      sha256 "7d01c5e6cb0f06efdbb5fe5027df0c255a401039b4320cb79688dc3142d94d18"

      def install
        bin.install "devlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.7.0/devlog_0.7.0_darwin_arm64.tar.gz"
      sha256 "b5005c86a935a42563e9e606a840852602e682210624387d00100ee641e05026"

      def install
        bin.install "devlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.7.0/devlog_0.7.0_linux_amd64.tar.gz"
      sha256 "c6cc3908d32a1b25edb4d358f70a8b7474d4b108bc50e8796cabde2a439ab452"
      def install
        bin.install "devlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.7.0/devlog_0.7.0_linux_arm64.tar.gz"
      sha256 "f8908cd913cfbab14499b4da21d4de086e9135f36cd7046797a7bf886e7f445f"
      def install
        bin.install "devlog"
      end
    end
  end

  test do
    system "#{bin}/devlog", "--version"
  end
end
