# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devlog < Formula
  desc "CLI tool for DevLog Daily - Journal your development progress"
  homepage "https://devlog.asd09.com"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.5.0/devlog_0.5.0_darwin_amd64.tar.gz"
      sha256 "609e05f744b6b6f76a38b8f272b75a9469c807ae2ad3f255d97e2da3ab321007"

      def install
        bin.install "devlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.5.0/devlog_0.5.0_darwin_arm64.tar.gz"
      sha256 "32f31025317aa3039e27691e5b4a1afc6f50d0f65ad5d2e6c6795676ac92048e"

      def install
        bin.install "devlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.5.0/devlog_0.5.0_linux_amd64.tar.gz"
      sha256 "3f8f0f9762821752f0609ccb96b1f98c6f6b12e57f5f036a3da3b3613a65427b"
      def install
        bin.install "devlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leffen/devlog-cli/releases/download/v0.5.0/devlog_0.5.0_linux_arm64.tar.gz"
      sha256 "521e2023307319a8c06bec941126cbf1b2c064d861a298fc688675eeba0503cb"
      def install
        bin.install "devlog"
      end
    end
  end

  test do
    system "#{bin}/devlog", "--version"
  end
end
